package in.ashokit.model;

import java.time.OffsetDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "query_result")
public class QueryResult {
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Store which registration number this belongs to
    @Column(name = "reg_no", nullable = false)
    private String regNo;

    // Final SQL might be long—set a generous length
    @Column(name = "final_query", length = 4000, nullable = false)
    private String finalQuery;

    // When it was saved
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    public QueryResult() {}

    // Convenience constructor for quick saves
    public QueryResult(String regNo, String finalQuery, OffsetDateTime createdAt) {
        this.regNo = regNo;
        this.finalQuery = finalQuery;
        this.createdAt = createdAt;
    }

    public Long getId() { return id; /* usually generated by DB */ }

    public String getRegNo() { return regNo; }
    public void setRegNo(String regNo) { this.regNo = regNo; }

    public String getFinalQuery() { return finalQuery; }
    public void setFinalQuery(String finalQuery) { this.finalQuery = finalQuery; }

    public OffsetDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(OffsetDateTime createdAt) { this.createdAt = createdAt; }

    @Override
    public String toString() {
        return "QueryResult{id=" + id + ", regNo='" + regNo + "', createdAt=" + createdAt + "}";
    }
	

}
